# Generated by Django 2.1.7 on 2019-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_site', models.CharField(max_length=100, verbose_name='起点')),
                ('to_site', models.CharField(max_length=100, verbose_name='终点')),
                ('category', models.CharField(max_length=100, verbose_name='标签/分类')),
                ('trip_mode', models.CharField(max_length=100, verbose_name='出行方式')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('deadline', models.DateTimeField(null=True, verbose_name='截止时间')),
                ('trip_time', models.DateTimeField(verbose_name='计划出行时间')),
                ('pub_username', models.CharField(max_length=100, verbose_name='发布者昵称')),
                ('pub_name', models.CharField(max_length=100, verbose_name='发布者姓名')),
                ('pub_no', models.CharField(max_length=100, verbose_name='发布者学号/工号')),
                ('pub_wechat', models.CharField(max_length=100, verbose_name='发布者微信ID')),
                ('pub_gender', models.CharField(max_length=100, verbose_name='发布者性别')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('num_need', models.IntegerField(verbose_name='需要人数')),
                ('num_have', models.IntegerField(default=0, verbose_name='已有人数')),
                ('full', models.BooleanField(default=False, verbose_name='是否人数已满')),
                ('ended', models.BooleanField(default=False, verbose_name='是否已结束')),
                ('canceled', models.BooleanField(default=False, verbose_name='是否已取消')),
                ('auth_gender', models.IntegerField(verbose_name='允许加入者性别')),
            ],
        ),
        migrations.CreateModel(
            name='JoinCarpoolPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_no', models.CharField(max_length=100, verbose_name='参加者的学号/工号')),
                ('join_username', models.CharField(max_length=100, verbose_name='参加者的昵称')),
                ('join_name', models.CharField(max_length=100, verbose_name='参加者的姓名')),
                ('join_wechat', models.CharField(max_length=100, verbose_name='参加者的微信ID')),
                ('join_gender', models.CharField(max_length=100, verbose_name='参加者的性别')),
                ('join_plan_id', models.IntegerField(verbose_name='所参加事件在Plan表中的序号')),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('ended', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('quitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JoinStudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_no', models.CharField(max_length=100, verbose_name='参加者的学号/工号')),
                ('join_username', models.CharField(max_length=100, verbose_name='参加者的昵称')),
                ('join_name', models.CharField(max_length=100, verbose_name='参加者的姓名')),
                ('join_wechat', models.CharField(max_length=100, verbose_name='参加者的微信ID')),
                ('join_gender', models.CharField(max_length=100, verbose_name='参加者的性别')),
                ('join_plan_id', models.IntegerField(verbose_name='所参加事件在Plan表中的序号')),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('ended', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('quitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='标签/分类')),
                ('duration', models.IntegerField(verbose_name='时长')),
                ('study_mode', models.CharField(max_length=100, null=True, verbose_name='学习方式')),
                ('study_place', models.CharField(max_length=100, null=True, verbose_name='学习地点')),
                ('start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='计划结束时间')),
                ('deadline', models.DateTimeField(null=True, verbose_name='报名截止时间')),
                ('pub_username', models.CharField(max_length=100, verbose_name='发布者昵称')),
                ('pub_name', models.CharField(max_length=100, verbose_name='发布者姓名')),
                ('pub_no', models.CharField(max_length=100, verbose_name='发布者学号/工号')),
                ('pub_wechat', models.CharField(max_length=100, verbose_name='发布者微信ID')),
                ('pub_gender', models.CharField(max_length=100, verbose_name='发布者性别')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('num_need', models.IntegerField(verbose_name='需要人数')),
                ('num_have', models.IntegerField(default=0, verbose_name='已有人数')),
                ('full', models.BooleanField(default=False, verbose_name='是否人数已满')),
                ('ended', models.BooleanField(default=False, verbose_name='是否已结束')),
                ('canceled', models.BooleanField(default=False, verbose_name='是否已取消')),
                ('auth_gender', models.IntegerField(verbose_name='允许加入者性别')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='密码')),
                ('no', models.CharField(max_length=100, verbose_name='学号/工号')),
                ('identity', models.CharField(max_length=100, verbose_name='身份')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=100, verbose_name='性别')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('avatar', models.ImageField(null=True, upload_to='static/avatar')),
                ('mail', models.CharField(max_length=100, verbose_name='邮箱')),
                ('weChat_id', models.CharField(max_length=100, verbose_name='微信ID')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('reg_time', models.DateTimeField(max_length=100, verbose_name='注册时间')),
                ('credit', models.IntegerField(default=100, verbose_name='信誉积分')),
            ],
        ),
    ]
