# Generated by Django 2.1.7 on 2019-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHubSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200, verbose_name='简介')),
                ('category', models.CharField(max_length=100, verbose_name='标签/分类')),
                ('duration', models.IntegerField(verbose_name='时长')),
                ('study_mode', models.CharField(max_length=100, null=True, verbose_name='学习方式')),
                ('study_place', models.CharField(max_length=100, null=True, verbose_name='学习地点')),
                ('start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='计划结束时间')),
                ('deadline', models.DateTimeField(null=True, verbose_name='报名截止时间')),
                ('pub_username', models.CharField(max_length=100, verbose_name='发布者昵称')),
                ('pub_name', models.CharField(max_length=100, verbose_name='发布者姓名')),
                ('pub_no', models.CharField(max_length=100, verbose_name='发布者学号/工号')),
                ('pub_wechat', models.CharField(max_length=100, verbose_name='发布者微信ID')),
                ('pub_gender', models.CharField(max_length=100, verbose_name='发布者性别')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('num_need', models.IntegerField(verbose_name='需要人数')),
                ('num_have', models.IntegerField(default=0, verbose_name='已有人数')),
                ('full', models.BooleanField(default=False, verbose_name='是否人数已满')),
                ('ended', models.BooleanField(default=False, verbose_name='是否已结束')),
                ('canceled', models.BooleanField(default=False, verbose_name='是否已取消')),
                ('auth_gender', models.IntegerField(verbose_name='允许加入者性别')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
