# Generated by Django 2.1.7 on 2019-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHubSite', '0002_auto_20190305_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='个性签名/状态'),
        ),
    ]
