# Generated by Django 2.1.7 on 2019-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHubSite', '0003_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplans',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='users',
            name='identity',
            field=models.CharField(max_length=100, null=True, verbose_name='身份'),
        ),
    ]
