# Generated by Django 2.1.7 on 2019-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHubSite', '0007_gameplans_joingameplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplans',
            name='duration',
            field=models.CharField(max_length=100, null=True, verbose_name='持续时间'),
        ),
    ]
